const fs = require('fs')
const data = {"fn": "aW1wb3J0IHdlYnB1c2ggZnJvbSAnbnBtOndlYi1wdXNoQDMuNi43JwoKY29uc3QgY29yc0hlYWRlcnMgPSB7CiAgJ0FjY2Vzcy1Db250cm9sLUFsbG93LU9yaWdpbic6ICcqJywKICAnQWNjZXNzLUNvbnRyb2wtQWxsb3ctSGVhZGVycyc6ICdhdXRob3JpemF0aW9uLCB4LWNsaWVudC1pbmZvLCBhcGlrZXksIGNvbnRlbnQtdHlwZScsCn0KCkRlbm8uc2VydmUoYXN5bmMgKHJlcSkgPT4gewogIGlmIChyZXEubWV0aG9kID09PSAnT1BUSU9OUycpIHJldHVybiBuZXcgUmVzcG9uc2UoJ29rJywgeyBoZWFkZXJzOiBjb3JzSGVhZGVycyB9KQoKICB0cnkgewogICAgY29uc3QgeyB0aXRsZSwgYm9keSwgdXJsLCBzdWJzY3JpcHRpb25zIH0gPSBhd2FpdCByZXEuanNvbigpCgogICAgY29uc3QgVkFQSURfUFVCTElDX0tFWSA9IERlbm8uZW52LmdldCgnVkFQSURfUFVCTElDX0tFWScpIHx8ICdCRWw2MmlVWWdVaXZ4SWt2Njl5VmlFdWlCSWEtSWI5LVNrdk1lQXRBM0xGZ0R6a3J4WkpqU2dTbmZja2paSmdMUXlqNVEzYXFFVm5YS1pLSlBFUUlMS1knCiAgICBjb25zdCBWQVBJRF9QUklWQVRFX0tFWSA9IERlbm8uZW52LmdldCgnVkFQSURfUFJJVkFURV9LRVknKSB8fCAnJwoKICAgIHdlYnB1c2guc2V0VmFwaWREZXRhaWxzKAogICAgICAnbWFpbHRvOmhlbGxvQG51cnNlcGFzc3BvcnRhZnJpY2EuY29tJywKICAgICAgVkFQSURfUFVCTElDX0tFWSwKICAgICAgVkFQSURfUFJJVkFURV9LRVkKICAgICkKCiAgICBjb25zdCBwYXlsb2FkID0gSlNPTi5zdHJpbmdpZnkoeyB0aXRsZSwgYm9keSwgdXJsIH0pCiAgICBsZXQgc2VudCA9IDAKICAgIGxldCBmYWlsZWQgPSAwCgogICAgZm9yIChjb25zdCBzdWIgb2Ygc3Vic2NyaXB0aW9ucykgewogICAgICB0cnkgewogICAgICAgIGNvbnN0IHN1YnNjcmlwdGlvbiA9IEpTT04ucGFyc2Uoc3ViLnN1YnNjcmlwdGlvbikKICAgICAgICBhd2FpdCB3ZWJwdXNoLnNlbmROb3RpZmljYXRpb24oc3Vic2NyaXB0aW9uLCBwYXlsb2FkKQogICAgICAgIHNlbnQrKwogICAgICB9IGNhdGNoIChlcnIpIHsKICAgICAgICBjb25zb2xlLmVycm9yKCdGYWlsZWQ6JywgZXJyLm1lc3NhZ2UpCiAgICAgICAgZmFpbGVkKysKICAgICAgfQogICAgfQoKICAgIHJldHVybiBuZXcgUmVzcG9uc2UoCiAgICAgIEpTT04uc3RyaW5naWZ5KHsgc3VjY2VzczogdHJ1ZSwgc2VudCwgZmFpbGVkIH0pLAogICAgICB7IGhlYWRlcnM6IHsgLi4uY29yc0hlYWRlcnMsICdDb250ZW50LVR5cGUnOiAnYXBwbGljYXRpb24vanNvbicgfSB9CiAgICApCiAgfSBjYXRjaCAoZXJyb3IpIHsKICAgIHJldHVybiBuZXcgUmVzcG9uc2UoCiAgICAgIEpTT04uc3RyaW5naWZ5KHsgZXJyb3I6IGVycm9yLm1lc3NhZ2UgfSksCiAgICAgIHsgc3RhdHVzOiA1MDAsIGhlYWRlcnM6IHsgLi4uY29yc0hlYWRlcnMsICdDb250ZW50LVR5cGUnOiAnYXBwbGljYXRpb24vanNvbicgfSB9CiAgICApCiAgfQp9KQo="}

// Fix deprecated meta tag in index.html
let html = fs.readFileSync('index.html', 'utf8')
html = html.replace(
  '<meta name="apple-mobile-web-app-capable" content="yes" />',
  '<meta name="mobile-web-app-capable" content="yes" />\n    <meta name="apple-mobile-web-app-capable" content="yes" />'
)
fs.writeFileSync('index.html', html)
console.log('Meta tag fixed')

// Write edge function
if (!fs.existsSync('supabase/functions/send-push-notification')) {
  fs.mkdirSync('supabase/functions/send-push-notification', { recursive: true })
}
fs.writeFileSync('supabase/functions/send-push-notification/index.ts', Buffer.from(data.fn, 'base64').toString('utf8'))
console.log('Edge function written')
console.log('Done')
