const fs = require('fs')
const files = {"theme": "aW1wb3J0IHsgY3JlYXRlQ29udGV4dCwgdXNlQ29udGV4dCwgdXNlU3RhdGUsIHVzZUVmZmVjdCB9IGZyb20gJ3JlYWN0JwoKZXhwb3J0IGNvbnN0IFRIRU1FUyA9IHsKICBvY2VhbjogeyBuYW1lOiAnT2NlYW4nLCBlbW9qaTogJ/CfjIonLCBwcmltYXJ5OiAnIzBBMjU0MCcsIHNlY29uZGFyeTogJyMwMDg5N0InLCBhY2NlbnQ6ICcjRjRBMzAwJywgZ3JhZGllbnQ6ICdsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCAjMEEyNTQwLCAjMUUzQTVGKScsIGNhcmRHcmFkaWVudDogJ2xpbmVhci1ncmFkaWVudCgxMzVkZWcsICM0RjQ2RTUsICM3QzNBRUQpJywgc2ltR3JhZGllbnQ6ICdsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCAjRjQzRjVFLCAjRUM0ODk5KScsIGJnOiAnI0Y3RjlGQycsIGRhcms6IGZhbHNlIH0sCiAgZGFyazogeyBuYW1lOiAnRGFyaycsIGVtb2ppOiAn8J+MmScsIHByaW1hcnk6ICcjMEYwRjFBJywgc2Vjb25kYXJ5OiAnIzYzNjZGMScsIGFjY2VudDogJyNGNTlFMEInLCBncmFkaWVudDogJ2xpbmVhci1ncmFkaWVudCgxMzVkZWcsICMwRjBGMUEsICMxRTFCNEIpJywgY2FyZEdyYWRpZW50OiAnbGluZWFyLWdyYWRpZW50KDEzNWRlZywgIzFFMUI0QiwgIzMxMkU4MSknLCBzaW1HcmFkaWVudDogJ2xpbmVhci1ncmFkaWVudCgxMzVkZWcsICM2MzY2RjEsICM4QjVDRjYpJywgYmc6ICcjMEYwRjFBJywgZGFyazogdHJ1ZSB9LAogIHJvc2U6IHsgbmFtZTogJ1Jvc2UnLCBlbW9qaTogJ/CfjLknLCBwcmltYXJ5OiAnIzg4MTMzNycsIHNlY29uZGFyeTogJyNGNDNGNUUnLCBhY2NlbnQ6ICcjRkI3MTg1JywgZ3JhZGllbnQ6ICdsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCAjODgxMzM3LCAjQkUxMjNDKScsIGNhcmRHcmFkaWVudDogJ2xpbmVhci1ncmFkaWVudCgxMzVkZWcsICNGNDNGNUUsICNGQjcxODUpJywgc2ltR3JhZGllbnQ6ICdsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCAjQkUxMjNDLCAjRjQzRjVFKScsIGJnOiAnI0ZGRjFGMicsIGRhcms6IGZhbHNlIH0sCiAgbWlkbmlnaHQ6IHsgbmFtZTogJ01pZG5pZ2h0JywgZW1vamk6ICfwn4yDJywgcHJpbWFyeTogJyMwRjBGMUEnLCBzZWNvbmRhcnk6ICcjNjM2NkYxJywgYWNjZW50OiAnI0Y1OUUwQicsIGdyYWRpZW50OiAnbGluZWFyLWdyYWRpZW50KDEzNWRlZywgIzBGMEYxQSwgIzFFMUI0QiknLCBjYXJkR3JhZGllbnQ6ICdsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCAjMUUxQjRCLCAjMzEyRTgxKScsIHNpbUdyYWRpZW50OiAnbGluZWFyLWdyYWRpZW50KDEzNWRlZywgIzYzNjZGMSwgIzhCNUNGNiknLCBiZzogJyMwRjBGMUEnLCBkYXJrOiB0cnVlIH0sCiAgZm9yZXN0OiB7IG5hbWU6ICdGb3Jlc3QnLCBlbW9qaTogJ/CfjL8nLCBwcmltYXJ5OiAnIzE0NTMyRCcsIHNlY29uZGFyeTogJyMxNkEzNEEnLCBhY2NlbnQ6ICcjODZFRkFDJywgZ3JhZGllbnQ6ICdsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCAjMTQ1MzJELCAjMTY2NTM0KScsIGNhcmRHcmFkaWVudDogJ2xpbmVhci1ncmFkaWVudCgxMzVkZWcsICMxNkEzNEEsICMyMkM1NUUpJywgc2ltR3JhZGllbnQ6ICdsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCAjMTU4MDNELCAjMTZBMzRBKScsIGJnOiAnI0YwRkRGNCcsIGRhcms6IGZhbHNlIH0sCiAgc3VucmlzZTogeyBuYW1lOiAnU3VucmlzZScsIGVtb2ppOiAn8J+MhScsIHByaW1hcnk6ICcjN0MyRDEyJywgc2Vjb25kYXJ5OiAnI0VBNTgwQycsIGFjY2VudDogJyNGQ0QzNEQnLCBncmFkaWVudDogJ2xpbmVhci1ncmFkaWVudCgxMzVkZWcsICM3QzJEMTIsICNDMjQxMEMpJywgY2FyZEdyYWRpZW50OiAnbGluZWFyLWdyYWRpZW50KDEzNWRlZywgI0VBNTgwQywgI0Y5NzMxNiknLCBzaW1HcmFkaWVudDogJ2xpbmVhci1ncmFkaWVudCgxMzVkZWcsICNEQzI2MjYsICNFQTU4MEMpJywgYmc6ICcjRkZGN0VEJywgZGFyazogZmFsc2UgfSwKICBsYXZlbmRlcjogeyBuYW1lOiAnTGF2ZW5kZXInLCBlbW9qaTogJ/CfkpwnLCBwcmltYXJ5OiAnIzRDMUQ5NScsIHNlY29uZGFyeTogJyM3QzNBRUQnLCBhY2NlbnQ6ICcjQzRCNUZEJywgZ3JhZGllbnQ6ICdsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCAjNEMxRDk1LCAjNUIyMUI2KScsIGNhcmRHcmFkaWVudDogJ2xpbmVhci1ncmFkaWVudCgxMzVkZWcsICM3QzNBRUQsICM5MzMzRUEpJywgc2ltR3JhZGllbnQ6ICdsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCAjNkQyOEQ5LCAjN0MzQUVEKScsIGJnOiAnI0Y1RjNGRicsIGRhcms6IGZhbHNlIH0sCiAgc2FoYXJhOiB7IG5hbWU6ICdTYWhhcmEnLCBlbW9qaTogJ/CfjI0nLCBwcmltYXJ5OiAnIzc4MzUwRicsIHNlY29uZGFyeTogJyNEOTc3MDYnLCBhY2NlbnQ6ICcjRkNEMzREJywgZ3JhZGllbnQ6ICdsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCAjNzgzNTBGLCAjOTI0MDBFKScsIGNhcmRHcmFkaWVudDogJ2xpbmVhci1ncmFkaWVudCgxMzVkZWcsICNEOTc3MDYsICNGNTlFMEIpJywgc2ltR3JhZGllbnQ6ICdsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCAjQjQ1MzA5LCAjRDk3NzA2KScsIGJnOiAnI0ZGRkJFQicsIGRhcms6IGZhbHNlIH0sCiAgbW9ub2Nocm9tZTogeyBuYW1lOiAnTW9ubycsIGVtb2ppOiAn4qybJywgcHJpbWFyeTogJyMxMTE4MjcnLCBzZWNvbmRhcnk6ICcjMzc0MTUxJywgYWNjZW50OiAnIzlDQTNBRicsIGdyYWRpZW50OiAnbGluZWFyLWdyYWRpZW50KDEzNWRlZywgIzExMTgyNywgIzFGMjkzNyknLCBjYXJkR3JhZGllbnQ6ICdsaW5lYXItZ3JhZGllbnQoMTM1ZGVnLCAjMzc0MTUxLCAjNEI1NTYzKScsIHNpbUdyYWRpZW50OiAnbGluZWFyLWdyYWRpZW50KDEzNWRlZywgIzFGMjkzNywgIzM3NDE1MSknLCBiZzogJyNGOUZBRkInLCBkYXJrOiBmYWxzZSB9LAp9Cgpjb25zdCBUaGVtZUNvbnRleHQgPSBjcmVhdGVDb250ZXh0KG51bGwpCgpleHBvcnQgZnVuY3Rpb24gVGhlbWVQcm92aWRlcih7IGNoaWxkcmVuIH0pIHsKICBjb25zdCBbdGhlbWVOYW1lLCBzZXRUaGVtZU5hbWVdID0gdXNlU3RhdGUoKCkgPT4gewogICAgdHJ5IHsKICAgICAgY29uc3Qgc2F2ZWQgPSBsb2NhbFN0b3JhZ2UuZ2V0SXRlbSgnbnBhLXRoZW1lJykKICAgICAgaWYgKHNhdmVkICYmIFRIRU1FU1tzYXZlZF0pIHJldHVybiBzYXZlZAogICAgICBpZiAod2luZG93Lm1hdGNoTWVkaWEgJiYgd2luZG93Lm1hdGNoTWVkaWEoJyhwcmVmZXJzLWNvbG9yLXNjaGVtZTogZGFyayknKS5tYXRjaGVzKSByZXR1cm4gJ2RhcmsnCiAgICAgIHJldHVybiAnb2NlYW4nCiAgICB9IGNhdGNoIHsgcmV0dXJuICdvY2VhbicgfQogIH0pCgogIGNvbnN0IHRoZW1lID0gVEhFTUVTW3RoZW1lTmFtZV0gfHwgVEhFTUVTLm9jZWFuCiAgY29uc3QgaXNEYXJrID0gdGhlbWUuZGFyayB8fCBmYWxzZQoKICB1c2VFZmZlY3QoKCkgPT4gewogICAgY29uc3QgbWVkaWFRdWVyeSA9IHdpbmRvdy5tYXRjaE1lZGlhKCcocHJlZmVycy1jb2xvci1zY2hlbWU6IGRhcmspJykKICAgIGZ1bmN0aW9uIGhhbmRsZUNoYW5nZShlKSB7CiAgICAgIGNvbnN0IHNhdmVkID0gbG9jYWxTdG9yYWdlLmdldEl0ZW0oJ25wYS10aGVtZScpCiAgICAgIGlmICghc2F2ZWQpIHNldFRoZW1lTmFtZShlLm1hdGNoZXMgPyAnZGFyaycgOiAnb2NlYW4nKQogICAgfQogICAgbWVkaWFRdWVyeS5hZGRFdmVudExpc3RlbmVyKCdjaGFuZ2UnLCBoYW5kbGVDaGFuZ2UpCiAgICByZXR1cm4gKCkgPT4gbWVkaWFRdWVyeS5yZW1vdmVFdmVudExpc3RlbmVyKCdjaGFuZ2UnLCBoYW5kbGVDaGFuZ2UpCiAgfSwgW10pCgogIHVzZUVmZmVjdCgoKSA9PiB7CiAgICBpZiAoaXNEYXJrKSB7CiAgICAgIGRvY3VtZW50LmRvY3VtZW50RWxlbWVudC5jbGFzc0xpc3QuYWRkKCdkYXJrJykKICAgICAgZG9jdW1lbnQuYm9keS5zdHlsZS5iYWNrZ3JvdW5kID0gdGhlbWUuYmcKICAgICAgZG9jdW1lbnQuYm9keS5zdHlsZS5jb2xvciA9ICcjRjFGNUY5JwogICAgfSBlbHNlIHsKICAgICAgZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LmNsYXNzTGlzdC5yZW1vdmUoJ2RhcmsnKQogICAgICBkb2N1bWVudC5ib2R5LnN0eWxlLmJhY2tncm91bmQgPSB0aGVtZS5iZwogICAgICBkb2N1bWVudC5ib2R5LnN0eWxlLmNvbG9yID0gJyMwQTI1NDAnCiAgICB9CiAgfSwgW2lzRGFyaywgdGhlbWUuYmddKQoKICBmdW5jdGlvbiBzZXRUaGVtZShuYW1lKSB7CiAgICBpZiAoVEhFTUVTW25hbWVdKSB7CiAgICAgIHNldFRoZW1lTmFtZShuYW1lKQogICAgICB0cnkgeyBsb2NhbFN0b3JhZ2Uuc2V0SXRlbSgnbnBhLXRoZW1lJywgbmFtZSkgfSBjYXRjaCB7fQogICAgfQogIH0KCiAgZnVuY3Rpb24gdG9nZ2xlRGFya01vZGUoKSB7CiAgICBpZiAoaXNEYXJrKSB7IHNldFRoZW1lKCdvY2VhbicpIH0gZWxzZSB7IHNldFRoZW1lKCdkYXJrJykgfQogIH0KCiAgcmV0dXJuICgKICAgIDxUaGVtZUNvbnRleHQuUHJvdmlkZXIgdmFsdWU9e3sgdGhlbWUsIHRoZW1lTmFtZSwgc2V0VGhlbWUsIHRoZW1lczogVEhFTUVTLCBpc0RhcmssIHRvZ2dsZURhcmtNb2RlIH19PgogICAgICB7Y2hpbGRyZW59CiAgICA8L1RoZW1lQ29udGV4dC5Qcm92aWRlcj4KICApCn0KCmV4cG9ydCBmdW5jdGlvbiB1c2VUaGVtZSgpIHsKICBjb25zdCBjb250ZXh0ID0gdXNlQ29udGV4dChUaGVtZUNvbnRleHQpCiAgaWYgKCFjb250ZXh0KSByZXR1cm4geyB0aGVtZTogVEhFTUVTLm9jZWFuLCB0aGVtZU5hbWU6ICdvY2VhbicsIHNldFRoZW1lOiAoKSA9PiB7fSwgdGhlbWVzOiBUSEVNRVMsIGlzRGFyazogZmFsc2UsIHRvZ2dsZURhcmtNb2RlOiAoKSA9PiB7fSB9CiAgcmV0dXJuIGNvbnRleHQKfQo="}

fs.writeFileSync('src/contexts/ThemeContext.jsx', Buffer.from(files.theme, 'base64').toString('utf8'))
console.log('ThemeContext updated')

// Add dark mode toggle to Sidebar
let sidebar = fs.readFileSync('src/components/layout/Sidebar.jsx', 'utf8')
if (!sidebar.includes('toggleDarkMode')) {
  // Add Moon/Sun import
  sidebar = sidebar.replace(
    "import { LayoutDashboard, BookOpen, Activity, Award, User, CreditCard, LogOut, ClipboardList, Gift, Settings, Info, MessageCircle, Trophy, Zap } from 'lucide-react'",
    "import { LayoutDashboard, BookOpen, Activity, Award, User, CreditCard, LogOut, ClipboardList, Gift, Settings, Info, MessageCircle, Trophy, Zap, Moon, Sun } from 'lucide-react'"
  )
  // Add toggleDarkMode to useTheme
  sidebar = sidebar.replace(
    "const { theme: rawTheme } = useTheme()",
    "const { theme: rawTheme, isDark, toggleDarkMode } = useTheme()"
  )
  // Add toggle button before sign out
  sidebar = sidebar.replace(
    "<button onClick={handleSignOut}",
    `<button onClick={toggleDarkMode}
          style={{ width: '100%', display: 'flex', alignItems: 'center', gap: '10px', padding: '10px 12px', borderRadius: '12px', background: 'none', border: 'none', cursor: 'pointer', color: 'rgba(255,255,255,0.55)', fontSize: '13px', fontWeight: '600', marginBottom: '4px' }}>
          {isDark ? <Sun size={17} /> : <Moon size={17} />}
          {isDark ? 'Light Mode' : 'Dark Mode'}
        </button>
        <button onClick={handleSignOut}`
  )
  fs.writeFileSync('src/components/layout/Sidebar.jsx', sidebar)
  console.log('Sidebar updated with dark mode toggle')
}

// Add dark mode toggle to MobileNav bottom bar
let nav = fs.readFileSync('src/components/layout/MobileNav.jsx', 'utf8')
if (!nav.includes('toggleDarkMode')) {
  nav = nav.replace(
    "import { useState } from 'react'",
    "import { useState } from 'react'"
  )
  nav = nav.replace(
    "  const { profile } = useAuth()",
    "  const { profile } = useAuth()\n  const { isDark, toggleDarkMode } = require('../../contexts/ThemeContext').useTheme ? require('../../contexts/ThemeContext').useTheme() : { isDark: false, toggleDarkMode: () => {} }"
  )
  fs.writeFileSync('src/components/layout/MobileNav.jsx', nav)
}

console.log('All done!')
